# Generated by Django 4.0.3 on 2024-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('owners', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
