# Generated by Django 4.0.3 on 2024-06-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gospeak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfps',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=15)),
                ('begin', models.CharField(max_length=50)),
                ('close', models.CharField(max_length=50)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='gospeak.groups')),
            ],
        ),
    ]
