# Generated by Django 4.0.3 on 2024-06-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospeak', '0004_proposals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='talks',
        ),
        migrations.AddField(
            model_name='events',
            name='talks',
            field=models.ManyToManyField(to='gospeak.proposals'),
        ),
    ]
