# Generated by Django 4.0.3 on 2024-07-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospeak', '0005_remove_events_talks_events_talks'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
