# Generated by Django 4.0.3 on 2024-07-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospeak', '0006_events_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
